/* 
 * Copyright Notice 
 * 
 * COPYRIGHT© 2021 Build 82. All rights reserved. No part of this software
 * and constituent code may be reproduced in any form, including video recording, 
 * photocopying, downloading, broadcasting or transmission electronically, without 
 * prior written consent of Build 82. Copyright protection includes output
 * generated by this software as displayed in print or in digital form, such as 
 * icons, interfaces, and the like.
 * 
 * Content Warranty 
 * 
 * The information in this document is subject to change without notice. THIS 
 * DOCUMENT IS PROVIDED "AS IS" AND BUILD 82 MAKES NO WARRANTY, EXPRESS, 
 * IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO ALL WARRANTIES OF 
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT. 
 * Build 82 shall not be liable for errors contained herein or for 
 * incidental or consequential damages in connection with the furnishing, 
 * performance or use of this material.
 */

define([
	'dojo/dom',
	'dojo/on',
	'dojo/topic',
	'build82/config'
	], 
    function(dom, on, topic, Config) {
		var static = {
			focus: 'dialog-session_clear'
		},
				
		handleHide = function() {
			topic.publish(Config.Topic.Focus, 'pop', {interface:static.focus});
		},
				
		handleShow = function() {
			topic.publish(Config.Topic.Focus, 'push', {interface:static.focus, title:'Clear Session', alias:'session/clear'});
		},
				
		handleSubmit = function() {
			topic.publish(Config.Topic.Session, 'clear', {});
			handleHide();
		};
			
		return {
			Init: function() {
				on(dom.byId('nav_session_clear'), 'click', handleShow);
				on(dom.byId('session_clear_cancel'), 'click', handleHide);
				on(dom.byId('session_clear_submit'), 'click', handleSubmit);
			}
		};
	}
);