/* 
 * Copyright Notice 
 * 
 * COPYRIGHT© 2021 Build 82. All rights reserved. No part of this software
 * and constituent code may be reproduced in any form, including video recording, 
 * photocopying, downloading, broadcasting or transmission electronically, without 
 * prior written consent of Build 82. Copyright protection includes output
 * generated by this software as displayed in print or in digital form, such as 
 * icons, interfaces, and the like.
 * 
 * Content Warranty 
 * 
 * The information in this document is subject to change without notice. THIS 
 * DOCUMENT IS PROVIDED "AS IS" AND BUILD 82 MAKES NO WARRANTY, EXPRESS, 
 * IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO ALL WARRANTIES OF 
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT. 
 * Build 82 shall not be liable for errors contained herein or for 
 * incidental or consequential damages in connection with the furnishing, 
 * performance or use of this material.
 */

define([
	'dojo/dom',
	'dojo/on',
	'dojo/topic',
	'build82/config'
	], 
    function(dom, on, topic, Config) {
		var static = {
			focus: 'dialog-setup',
			setup: {
				setup_export_marks: 1,
				setup_session_persist: 0,
				setup_record_clear: 0
			}
		},
				
		handleHide = function() {
			topic.publish(Config.Topic.Focus, 'pop', {interface:static.focus});
		},
				
		handleShow = function() {
			topic.publish(Config.Topic.Focus, 'push', {interface:static.focus, title:'Setup', alias:'setup'});
		},
				
		handleRestore = function(param_obj) {
			static.setup = Object.assign(static.setup, param_obj);
			
			for(var i in static.setup) {
				dom.byId(i).checked = static.setup[i];
			}
		},
		
		saveState = function() {
			for(var i in static.setup) {
				static.setup[i] = +dom.byId(i).checked;
			}
			
			topic.publish(Config.Topic.Setup, 'persist', {persist:{setup:static.setup}});
		},
		
		set = function(param_index, param_data) {
			static.setup[param_index] = param_data;
			dom.byId(param_index).checked = param_data;
		},
				
		retrieve = function(param_index) {
			if(param_index) {
				return static.setup['setup_'+param_index];
			}
			
			return static.setup;
		};
			
		return {
			Init: function() {
				on(dom.byId('nav_setup'), 'click', handleShow);
				on(dom.byId('setup_cancel'), 'click', handleHide);
				on(dom.byId('dialog-setup'), 'change', saveState);
				
				topic.subscribe(Config.Topic.Setup, function(command, obj) {
					switch(command) {
						case 'restore' :
							handleRestore(obj.setup);
							break;
					}
				});
			},
			Get: retrieve,
			Set: set
		};
	}
);